all: unistd_unix.out fread.out ifstream.out

unistd_unix.out: unistd_unix.cpp
	g++ -o $@ unistd_unix.cpp

fread.out: fread.cpp
	g++ -o $@ fread.cpp

ifstream.out: ifstream.cpp
	g++ -o $@ ifstream.cpp --std=c++11
